### ISSUE TITLE
[Java] Serialize pojo throws: java.lang.IllegalArgumentException: interface java.util.Map is not a super class of java.lang.Object

### ISSUE THREAD

**Issue by xiguashu** [alipay/fury#1021]
**Describe the bug**
When it serialize a pojo with a nested map field, it throws ' _java.lang.IllegalArgumentException: interface java.util.Map is not a super class of java.lang.Object_'

**Error stack**
```
java.lang.IllegalArgumentException: interface java.util.Map is not a super class of java.lang.Object

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:396)
	at com.google.common.reflect.TypeToken.getSupertype(TypeToken.java:372)
	at io.fury.type.TypeUtils.getMapKeyValueType(TypeUtils.java:429)
	at io.fury.serializers.MapSerializers$MapSerializer.getKVGenericType(MapSerializers.java:408)
	at io.fury.serializers.MapSerializers$MapSerializer.genericJavaWrite(MapSerializers.java:184)
	at io.fury.serializers.MapSerializers$MapSerializer.writeElements(MapSerializers.java:150)
	at io.fury.serializers.MapSerializers$MapSerializer.write(MapSerializers.java:110)
	at io.fury.serializers.MapSerializers$MapSerializer.write(MapSerializers.java:41)
	at io.fury.Fury.writeReferencableToJava(Fury.java:293)
	at io.fury.serializers.MapSerializers$MapSerializer.writeJavaRefOptimized(MapSerializers.java:734)
	at io.fury.serializers.MapSerializers$MapSerializer.javaKeyTypeFinalWrite(MapSerializers.java:253)
	at io.fury.serializers.MapSerializers$MapSerializer.genericJavaWrite(MapSerializers.java:206)
	at io.fury.serializers.MapSerializers$MapSerializer.writeElements(MapSerializers.java:150)
	at io.fury.serializers.MapSerializers$MapSerializer.write(MapSerializers.java:110)
	at io.fury.serializers.MapSerializers$MapSerializer.write(MapSerializers.java:41)
	at io.fury.Fury.writeNonReferenceToJava(Fury.java:363)
	at io.fury.serializers.ObjectSerializer.writeContainerFieldValue(ObjectSerializer.java:247)
	at io.fury.serializers.ObjectSerializer.writeContainerFields(ObjectSerializer.java:229)
	at io.fury.serializers.ObjectSerializer.write(ObjectSerializer.java:180)
	at io.fury.Fury.writeData(Fury.java:478)
	at io.fury.Fury.writeReferencableToJava(Fury.java:274)
	at io.fury.Fury.serializeInternal(Fury.java:245)
	at io.fury.Fury.serialize(Fury.java:182)
	at io.fury.Fury.serialize(Fury.java:163)
	at SerTest.test(SerTest.java:213)
```

**To Reproduce**
Here is the test code.
```
    class Pojo {
        Map<String, Object> map;
    }

    @Test
    public void test() {

        Fury fury = Fury.builder()
                .withLanguage(Language.JAVA)
                .requireClassRegistration(false)
                .withAsyncCompilationEnabled(true)
                .build();

        Pojo pojo = new Pojo();
        Map<String, Object> body = new HashMap<>();
        body.put("key", new HashMap<>());
        pojo.map = body;

        byte[] bytes = fury.serialize(pojo);

        fury = Fury.builder()
                .withLanguage(Language.JAVA)
                .requireClassRegistration(false)
                .withAsyncCompilationEnabled(true)
                .build();

        Object result = fury.deserialize(bytes);

    }
```
**Environment**
fury version: 0.11.2
java: 
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

**Comment by chaokunyang** [comment]
I can't reproduce it in fury v0.2.1, seems that you used a very old internal version of fury. Could you try latest fury out?

**Comment by chaokunyang** [comment]
Works fine on 0.2.1:
![image](https://github.com/alipay/fury/assets/12445254/6ae8c417-4266-4927-8eb5-62f879dd2943)
