### ISSUE TITLE
[Java]  deserializeJavaObject exception

### ISSUE THREAD

**Issue by sysmat** [alipay/fury#1035]
**Describe the bug**
When using `deserializeJavaObject` throws exception

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 95 out of bounds for byte[61]
	at java.base/java.lang.System.arraycopy(Native Method)
	at io.fury.serializer.StringSerializer.readJava11String(StringSerializer.java:241)
	at aris.FurySeralizationMain_UserFuryCodec_1571111118_118352462_184966243.read(FurySeralizationMain_UserFuryCodec_1571111118_118352462_184966243.java:99)
	at io.fury.Fury.readDataInternal(Fury.java:844)
	at io.fury.Fury.deserializeJavaObject(Fury.java:999)
	at io.fury.Fury.deserializeJavaObject(Fury.java:983)
	at aris.FurySeralizationMain.main(FurySeralizationMain.java:40)
```

**Expected behavior**
To create class

**To Reproduce**
1. java record, even if I use java class the same error

```java
public record User(Integer id, String name, RateEnum rate){};
public enum RateEnum {
    LOW, MEDIUM, HIGH
}
```

2. main

```java
public static void main(String[] args) {
 User user = new User(1, "Test", RateEnum.LOW);

  Fury fury = Fury.builder()
                .withLanguage(Language.JAVA)
                .requireClassRegistration(false)
                .build();

   fury.register(User.class);
   fury.register(RateEnum.class);
   byte[] bytes = fury.serialize(user);
   User result2 = fury.deserializeJavaObject(bytes, User.class);
```
**Screenshots**

**Environment (please complete the following information):**
- Windows 11
- jdk 21
- org.furyio:fury-core:0.2.1

**Comment by chaokunyang** [comment]
You should use fury.serializeJavaObject if you use deserializeJavaObject

**Comment by sysmat** [comment]
@chaokunyang thx, it works
