### ISSUE TITLE
Expect jit serializer but got class io.fury.serializer.CodegenSerializer$LazyInitBeanSerializer

### ISSUE THREAD

**Issue by qinzhikui** [alipay/fury#1104]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**
java.lang.IllegalArgumentException: Expect jit serializer but got class io.fury.serializer.CodegenSerializer$LazyInitBeanSerializer
	at io.fury.util.Utils.checkArgument(Utils.java:55) 
	at io.fury.serializer.CodegenSerializer$LazyInitBeanSerializer.getOrCreateGeneratedSerializer(CodegenSerializer.java:96) 
	at io.fury.serializer.CodegenSerializer$LazyInitBeanSerializer.write(CodegenSerializer.java:76) 
	at io.fury.Fury.writeData(Fury.java:483) 
	at io.fury.Fury.writeRef(Fury.java:283) 
	at io.fury.Fury.serialize(Fury.java:233) 
	at io.fury.Fury.serialize(Fury.java:193) 
	at io.fury.ThreadLocalFury.serialize(ThreadLocalFury.java:64) 

**Expected behavior**

**To Reproduce**
Steps to reproduce the behavior.
Please try to provide a reproducible script.

**Screenshots**

**Environment (please complete the following information):**
Fury 0.0.1, JDK11

**Comment by chaokunyang** [comment]
@qinzhikui Could you try fury 0.3.0? It should work

**Comment by qinzhikui** [comment]
By the way, what is the reason for this bug

**Comment by qinzhikui** [comment]
> @qinzhikui Could you try fury 0.3.0? It should work

By the way, what is the reason for this bug

**Comment by chaokunyang** [comment]
The jit created serializer didn't get updated into this serializer for circular self reference types. I fixed it several months before

**Comment by skarpushin** [comment]
I've just bumped into Exactly same issue with version 0.4.1.

**Comment by skarpushin** [comment]
Sorry, not immediately and most likely not SNAPSHOT version. Issue was not reproducible locally. Only when data transferred through several microservices. We already applied hotfix (reverted back to old (de)serialization approach). I don't know when there will be next time we can try Fury. Please let me know once new version is released.

**Comment by codenotknock** [comment]
When I did the Benchmark test，I've just bumped into Exactly same issue with version 0.5.1.

**Comment by chaokunyang** [comment]
> When I did the Benchmark test，I've just bumped into Exactly same issue with version 0.5.1.

Could you provide the reproduction code here? The fix won't be complex if we can reproduce it locally

**Comment by codenotknock** [comment]
```java
public class FurySerializer implements MySerializer {
    private Fury fury;

    public FurySerializer() {

        fury = Fury.builder().withLanguage(Language.JAVA)
            .withRefTracking(false)
            .requireClassRegistration(false)
            .build();
    }

    @Override
    public <T extends Serializable> byte[] serialize(T obj) {
        return fury.serialize(obj);
    }

    @Override
    public <T extends Serializable> T deSerialize(byte[] bytes, Class<T> clazz) {
        return (T) fury.deserialize(bytes);
    }
}
```
```java
@Warmup(iterations = 10, time = 2)
@Measurement(iterations = 30, batchSize = 100)
@Fork(2)
@State(Scope.Thread)
public class BaseJMH {
    static BaseEntity[] entityArray = new BaseEntity[entityCreators.length];
    static byte[][] entityBytesArray = new byte[entityCreators.length][];

    @Param(value = {"1", "1"})
    private int length;

    /**
     * 初始化 测试数据
     *
     * @param serializer
     */
    protected void init(MySerializer serializer) {
        try {
            for (int n = 0; n < entityCreators.length; n++) {
                entityArray[n] = entityCreators[n].create();
                entityBytesArray[n] = serializer.serialize(entityArray[n]);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * 序列化测试
     *
     * @param bh
     * @throws Exception
     */
    @Benchmark
    public void testMultiThreadSharedSingletonSerialize(Blackhole bh) throws Exception {
        MySerializer serializer = getSingletonSerializer();
        for (int n = 0; n < entityArray.length; n++) {
            bh.consume(serializer.serialize(entityArray[n]));
        }
        bh.consume(length);
    }

    /**
     * 反序列化测试
     *
     * @param bh
     * @throws Exception
     */
    @Benchmark
    public void testMultiThreadSharedSingletonDeserialize(Blackhole bh) throws Exception {
        MySerializer serializer = getSingletonSerializer();
        for (int n = 0; n < entityBytesArray.length; n++) {
            bh.consume(serializer.deSerialize(entityBytesArray[n], entityArray[n].getClass()));
        }
        bh.consume(length);
    }

    /**
     * 序列化测试
     *
     * @param bh
     * @throws Exception
     */
    @Benchmark
    public void testMultiThreadMultitonSerialize(Blackhole bh) throws Exception {
        MySerializer serializer = getMultitonSerializer();
        for (int n = 0; n < entityArray.length; n++) {
            bh.consume(serializer.serialize(entityArray[n]));
        }
        bh.consume(length);
    }

    /**
     * 反序列化测试
     *
     * @param bh
     * @throws Exception
     */
    @Benchmark
    public void testMultiThreadMultitonDeserialize(Blackhole bh) throws Exception {
        MySerializer serializer = getMultitonSerializer();
        for (int n = 0; n < entityBytesArray.length; n++) {
            bh.consume(serializer.deSerialize(entityBytesArray[n], entityArray[n].getClass()));
        }
        bh.consume(length);
    }

    protected MySerializer getMultitonSerializer() {
        return null;
    }


    protected MySerializer getSingletonSerializer() {
        return null;
    }

    protected String getClassName() {
        return null;
    }

    @Test
    public void doTest() throws RunnerException {
        Options opt = new OptionsBuilder()
            .include(getClassName())
            .build();
        new Runner(opt).run();
    }


}
```
```java
@Threads(8)
public class TestFurySerializer extends BaseJMH {

    static MySerializer singletonSerializer = SerializerCreatorFactory.FurySerializerCreator.INSTANCE.create();
    MySerializer multitonSerializer = SerializerCreatorFactory.FurySerializerCreator.INSTANCE.create();

    public TestFurySerializer() {
        init(singletonSerializer);
    }

    @Override
    public MySerializer getMultitonSerializer() {
        return singletonSerializer;
    }

    @Override
    public MySerializer getSingletonSerializer() {
        return multitonSerializer;
    }

    @Override
    public String getClassName() {
        return this.getClass().getSimpleName();
    }
    

}

```
```java
@Data
public class Consumer extends BaseEntity {
    private LocalDateTime modified;

    private long oid;

    private String ype;

    private String ick;

    private long tid;


    public static Consumer build() {
        Consumer consumer = new Consumer();

        consumer .setModified(LocalDateTime.now());
        consumer .setOid(216356211771L);
        consumer .setYpe("refund");
        consumer .setIck("302047");
        consumer .setTid(211771L);
        return consumer ;
    }

}
```

**Comment by kewbish** [comment]
@codenotknock Do you recall what the correct initialization definition when using multithreading is? We're running into the same issue on version 0.10.0 on Java version 22. 

Our current initialization code is:
```
private static Fury fury = Fury.builder().withLanguage(Language.JAVA).requireClassRegistration(false).build();
```

**Comment by chaokunyang** [comment]
> [@codenotknock](https://github.com/codenotknock) Do you recall what the correct initialization definition when using multithreading is? We're running into the same issue on version 0.10.0 on Java version 22.
> 
> Our current initialization code is:
> 
> ```
> private static Fury fury = Fury.builder().withLanguage(Language.JAVA).requireClassRegistration(false).build();
> ```
> 
> Edit for future readers: Fury has a specific thread-safe initializer, [see here](https://fury.apache.org/docs/guide/java_object_graph_guide/#quick-start).

You are using single Threaded Fury, please use multi threaded Fury

**Comment by chaokunyang** [comment]
Please reopen it if the issue still happen on fory latest version
