### ISSUE TITLE
[Scala] Serialization exception when a type is defined in a package object

### ISSUE THREAD

**Issue by ghostdogpr** [alipay/fury#1128]
**Describe the bug**
If you try to serialize anything that is defined inside a `package object`, it fails with an error like this:
```
Exception in thread "main" java.lang.RuntimeException: Create sequential serializer failed, 
class: class SomePackageObject.package$SomeClass
	at io.fury.serializer.CodegenSerializer.loadCodegenSerializer(CodegenSerializer.java:48)
	at io.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$2(ClassResolver.java:955)
	at io.fury.builder.JITContext.registerSerializerJITCallback(JITContext.java:132)
	at io.fury.resolver.ClassResolver.getObjectSerializerClass(ClassResolver.java:953)
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:908)
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:813)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1175)
	at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1107)
	at io.fury.Fury.writeRef(Fury.java:309)
	at io.fury.Fury.write(Fury.java:286)
	at io.fury.Fury.serialize(Fury.java:231)
	at io.fury.Fury.serialize(Fury.java:185)
```

**Expected behavior**
There should be no such error.

**To Reproduce**
```scala
import io.fury.Fury

package object SomePackageObject {
  case class SomeClass(value: Int)
}

object Reproducer extends App {
  val fury = Fury
    .builder()
    .withScalaOptimizationEnabled(true)
    .requireClassRegistration(false)
    .withRefTracking(true)
    .build()

  val p = SomePackageObject.SomeClass(1)
  println(fury.deserialize(fury.serialize(p)))
}
```

**Environment (please complete the following information):**
Tried with Fury 0.3.0 and 0.3.1, Scala 2.13.

**Comment by chaokunyang** [comment]
@ghostdogpr Thanks for creating this issue, I can reproduce it in my local machine. I will fix it in #1130
