### ISSUE TITLE
[Scala] Serialization exception when a class refers to another class inside a package object

### ISSUE THREAD

**Issue by ghostdogpr** [alipay/fury#1165]
**Describe the bug**
If you try to serialize a class that refers to something inside a `package object`, it fails with an error like this:
```
Exception in thread "main" java.lang.RuntimeException: Create sequential serializer failed, 
class: class com.devsisters.ck.benchmarks.Reproducer$SomeClass
	at io.fury.serializer.CodegenSerializer.loadCodegenSerializer(CodegenSerializer.java:48)
	at io.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$2(ClassResolver.java:999)
	at io.fury.builder.JITContext.registerSerializerJITCallback(JITContext.java:132)
	at io.fury.resolver.ClassResolver.getObjectSerializerClass(ClassResolver.java:997)
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:931)
	at io.fury.resolver.ClassResolver.getSerializerClass(ClassResolver.java:830)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1219)
	at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1151)
	at io.fury.Fury.writeRef(Fury.java:345)
	at io.fury.Fury.write(Fury.java:322)
	at io.fury.Fury.serialize(Fury.java:256)
	at io.fury.Fury.serialize(Fury.java:209)

```

**Expected behavior**
There should be no such error.

**To Reproduce**
```scala
import io.fury.Fury

package object O {
  case class Id(value: Int)
}

object Reproducer extends App {

  val fury = Fury
    .builder()
    .withScalaOptimizationEnabled(true)
    .requireClassRegistration(false)
    .withRefTracking(true)
    .build()

  import O._

  case class SomeClass(v: Id)
  val p = SomeClass(Id(1))
  println(fury.deserialize(fury.serialize(p)))
}

```

**Environment (please complete the following information):**
Tried with the latest snapshot, Scala 2.13.

**Comment by ghostdogpr** [comment]
By the way, I am interested in replacing Kryo with Fury, so I am testing serialization of a large object we use at work, which is why I find a lot of these issues. Thanks for the quick fixes!

**Comment by chaokunyang** [comment]
> By the way, I am interested in replacing Kryo with Fury, so I am testing serialization of a large object we use at work, which is why I find a lot of these issues. Thanks for the quick fixes!

You are welcome, thank you too for creating those issues. This helps us improve fury scala quickly.
