### ISSUE TITLE
ClassNotFoundException:SingletonImmutableBiMap

### ISSUE THREAD

**Issue by googlefan** [alipay/fury#1235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/alipay/issues) and found no similar issues.

### Version

Fury:4.1.0
OS: macOS
JDK:1.8
Guava:31.1

### Component(s)

Java

### Minimal reproduce step

I use 
<dependency>
    <groupId>org.furyio</groupId>
    <artifactId>fury-core</artifactId>
    <version>4.1.0</version>
</dependency>
in my project instead of Hession serialize protocal.

### What did you expect to see?

I want get success byte[] .

### What did you see instead?

Caused by: com.alipay.remoting.rpc.exception.RpcServerException: [Server]OriginErrorMsg: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.google.common.collect.SingletonImmutableBiMap. AdditionalErrorMsg: AYSNC process rpc request failed in RpcRequestProcessor, id=56
	at io.fury.serializer.collection.GuavaCollectionSerializers.loadClass(GuavaCollectionSerializers.java:411)
	at io.fury.serializer.collection.GuavaCollectionSerializers.registerDefaultSerializers(GuavaCollectionSerializers.java:385)

### Anything Else?

I don't know what caused this exception .I need some help to resolve it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by googlefan** [comment]
由于项目自身的guava 存在多个冲突的版本,应该是在项目启动时,某个类无法加载导致的, 定义统一的guava版本即可解决
