### ISSUE TITLE
[Java]Throw an exception in JMH on multi thread mode 

### ISSUE THREAD

**Issue by jiangguilong2000** [alipay/fury#711]
```java
@Fork(1)
@Threads(Threads.MAX)
@BenchmarkMode(Mode.Throughput)
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
@OutputTimeUnit(TimeUnit.SECONDS)
@State(Scope.Benchmark)
public class ProtoBenchMarkX {
    private SkillFire_S2C_Msg  skillFire_s2C_msg = DataUtil.build(SkillFire_S2C_Msg.class);
    private Fury fury;

    @Setup
    public void init() {
        try {
          byte[]  array = FileUtils.getByteArrayFromFile("message.txt");
            skillFire_s2C_msg= JSON.parseObject(array,SkillFire_S2C_Msg.class);
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
        fury = Fury.builder().withLanguage(Language.JAVA).withRefTracking(true).requireClassRegistration(false).build();

    }
    @Benchmark
    public byte[] furySerialize() {
        return fury.serialize(skillFire_s2C_msg);
    }
}
```
here is exception as follows:
```bash
java.lang.NullPointerException
	at io.fury.resolver.EnumStringResolver.resetWrite(EnumStringResolver.java:184)
	at io.fury.Fury.resetWrite(Fury.java:1142)
	at io.fury.Fury.serialize(Fury.java:242)
	at io.fury.Fury.serialize(Fury.java:183)
	at io.gamioo.sandbox.ProtoBenchMark.furySerialize(ProtoBenchMark.java:82)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_thrpt_jmhStub(ProtoBenchMark_furySerialize_jmhTest.java:142)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_Throughput(ProtoBenchMark_furySerialize_jmhTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
	at io.fury.collection.IdentityObjectIntMap.putOrGet(IdentityObjectIntMap.java:100)
	at io.fury.resolver.MapRefResolver.writeRefOrNull(MapRefResolver.java:82)
	at io.gamioo.sandbox.SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.writeFields$(SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.java:136)
	at io.gamioo.sandbox.SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.write(SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.java:313)
	at io.fury.Fury.writeData(Fury.java:485)
	at io.fury.Fury.writeRef(Fury.java:285)
	at io.fury.Fury.serialize(Fury.java:235)
	at io.fury.Fury.serialize(Fury.java:183)
	at io.gamioo.sandbox.ProtoBenchMark.furySerialize(ProtoBenchMark.java:82)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_thrpt_jmhStub(ProtoBenchMark_furySerialize_jmhTest.java:142)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_Throughput(ProtoBenchMark_furySerialize_jmhTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 8
	at io.fury.collection.IdentityObjectIntMap.putOrGet(IdentityObjectIntMap.java:100)
	at io.fury.resolver.MapRefResolver.writeRefOrNull(MapRefResolver.java:82)
	at io.gamioo.sandbox.SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.writeFields1$(SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.java:184)
	at io.gamioo.sandbox.SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.write(SkillFire_S2C_MsgFuryRefCodec_2131155096_1908153060_829010163.java:314)
	at io.fury.Fury.writeData(Fury.java:485)
	at io.fury.Fury.writeRef(Fury.java:285)
	at io.fury.Fury.serialize(Fury.java:235)
	at io.fury.Fury.serialize(Fury.java:183)
	at io.gamioo.sandbox.ProtoBenchMark.furySerialize(ProtoBenchMark.java:82)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_thrpt_jmhStub(ProtoBenchMark_furySerialize_jmhTest.java:142)
	at io.gamioo.sandbox.jmh_generated.ProtoBenchMark_furySerialize_jmhTest.furySerialize_Throughput(ProtoBenchMark_furySerialize_jmhTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by chaokunyang** [comment]
Fury is not thread safe, you should use thread safe fury. Please reference our document for further details about ThreadSafeFury
