### ISSUE TITLE
[Java]  class has register，but field class is not registered？

### ISSUE THREAD

**Issue by DemonJun** [alipay/fury#771]
During use, 2 classes were registered, and one class's sub-property class was not prompted that it's unregistered, but the other class did prompt that the sub-property class was unregistered.

pom.xml
```xml
<dependency>
	<groupId>org.roaringbitmap</groupId>
	<artifactId>RoaringBitmap</artifactId>
	<version>0.9.46</version>
</dependency>
<dependency>
	<groupId>com.clickhouse</groupId>
	<artifactId>clickhouse-java</artifactId>
	<version>0.4.6</version>
</dependency>
```
Roaring64Bitmap.class
```java
public class Roaring64Bitmap implements Externalizable, LongBitmapDataProvider {

  private HighLowContainer highLowContainer;
.....
}
```

UT
```java
private static final List<Class<?>> NEED_REGISTER_CLASS =
      List.of(Roaring64Bitmap.class, ClickHouseRowData.class);
  static Fury fury =
      Fury.builder()
          .withLanguage(Language.JAVA)
          .withClassLoader(Thread.currentThread().getContextClassLoader())
          // enable referecne tracking for shared/circular reference.
          // Disable it will have better performance if no duplciate reference.
          .withRefTracking(false)
          // compress int/long for smaller size
          .withNumberCompressed(true)
          .withStringCompressed(true)
          .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
          // .withMetaContextShareEnabled(false)
          // enable type forward/backward compatibility
          // disable it for small size and better performance.
          // .withCompatibleMode(CompatibleMode.COMPATIBLE)
          // enable async multi-threaded compilation.
          .withAsyncCompilationEnabled(true)
          .build();

  static {
    for (Class<?> aclass : NEED_REGISTER_CLASS) {
      fury.register(aclass);
    }
  }

  @Test
  public void test() {
    Roaring64Bitmap bitmap = new Roaring64Bitmap();
    for (int i = 0; i < 1000; i++) {
      bitmap.add(RandomUtil.randomLong(Long.MAX_VALUE));
    }

    byte[] bytes = fury.serializeJavaObject(bitmap);

    Roaring64Bitmap bitmap1 = fury.deserializeJavaObject(bytes, Roaring64Bitmap.class);
    Assertions.assertEquals(bitmap1, bitmap);

    ClickHouseRowData clickHouseRowData = new ClickHouseRowData();
    clickHouseRowData.column = ClickHouseColumn.of("a", ClickHouseDataType.String.name());
    clickHouseRowData.columnValues.put(
        ClickHouseColumn.of("a", ClickHouseDataType.String.name()), 1);

    bytes = fury.serializeJavaObject(clickHouseRowData);

    ClickHouseRowData clickHouseRowData1 =
        fury.deserializeJavaObject(bytes, ClickHouseRowData.class);
    Assertions.assertEquals(clickHouseRowData1, clickHouseRowData);
  }

  @Data
  @Accessors(chain = true)
  public static class ClickHouseRowData implements Serializable {
    private ClickHouseColumn column;
    private Map<ClickHouseColumn, Integer> columnValues;
    private long byteSize = 1;

    public ClickHouseRowData() {
      this.columnValues = Maps.newHashMapWithExpectedSize(50);
    }

    private ClickHouseRowData(Map<ClickHouseColumn, Integer> columnValues) {
      this.columnValues = columnValues;
    }
  }
```
Exception：
```txt
io.fury.exception.InsecureException: class com.clickhouse.data.ClickHouseColumn is not registered, if it's not the type you want to serialize, it may be a **vulnerability**. If it's not a vulnerability, registering class by `Fury#register` will have better performance, otherwise class name will be serialized too.

	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1016)
	at io.fury.resolver.ClassResolver.getClassInfo(ClassResolver.java:924)
	at io.fury.serializer.ObjectSerializer$FinalTypeField.<init>(ObjectSerializer.java:762)
	at io.fury.serializer.ObjectSerializer$FinalTypeField.<init>(ObjectSerializer.java:750)
	at io.fury.serializer.ObjectSerializer.buildFinalTypeField(ObjectSerializer.java:166)
	at io.fury.serializer.ObjectSerializer.buildFieldInfos(ObjectSerializer.java:130)
	at io.fury.serializer.ObjectSerializer.<init>(ObjectSerializer.java:104)
	at io.fury.serializer.ObjectSerializer.<init>(ObjectSerializer.java:82)
	at io.fury.serializer.Serializers.newSerializer(Serializers.java:60)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1030)
	at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:968)
	at io.fury.Fury.serializeJavaObject(Fury.java:939)
	at io.fury.Fury.serializeJavaObject(Fury.java:917)

```

**Comment by DemonJun** [comment]
通过调试，发现 Roaring64Bitmap 实现了 Externalizable 接口，自己创建的类 ClickHouseRowData 没有实现这个接口

**Comment by chaokunyang** [comment]
If a class  implements the `Externalizable` interface, if will be serialized be invoking `writeExternalizable`/`readExternalizable`. Maybe that's why the serialization succeed even the field class is not registered
