### ISSUE TITLE
Fury java version java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by tonysmz** [alipay/fury#821]
Thank you for reporting the problem!
Please make sure what you are reporting is a bug with reproducible steps. 

**Describe the bug**
fury version: 0.1.0
jdk version: java 11
Description:  java.lang.NegativeArraySizeException occurred when serialize list
stack print:
java.lang.NegativeArraySizeException: -2035644744

	at io.fury.memory.MemoryBuffer.ensure(MemoryBuffer.java:1877)
	at io.fury.memory.MemoryBuffer.grow(MemoryBuffer.java:1871)
	at io.fury.resolver.MapRefResolver.writeRefOrNull(MapRefResolver.java:68)
	at io.fury.Fury.writeRef(Fury.java:280)
	at io.fury.serializer.CollectionSerializers$CollectionSerializer.writeElements(CollectionSerializers.java:138)
	at io.fury.serializer.CollectionSerializers$CollectionSerializer.write(CollectionSerializers.java:115)
	at io.fury.serializer.CollectionSerializers$CollectionSerializer.write(CollectionSerializers.java:65)
	at io.fury.Fury.writeData(Fury.java:483)
	at io.fury.Fury.writeRef(Fury.java:283)
	at io.fury.Fury.serialize(Fury.java:233)
	at io.fury.Fury.serialize(Fury.java:181)

**Comment by chaokunyang** [comment]
@tonysmz could you provide the reproduction code?

**Comment by tonysmz** [comment]
> @tonysmz could you provide the reproduction code?

Sorry I can't, the List has more than 14M records from database, it can be serialized by jdk, but it very slow.

**Comment by chaokunyang** [comment]
> > @tonysmz could you provide the reproduction code?
> 
> Sorry I can't, the List has more than 14M records from database, it can be serialized by jdk, but it very slow.

The data deserialized by fury must be the data serialized by fury, rather than jdk serialized data. Fury compatibility is the user api level, rather than binary level

**Comment by tonysmz** [comment]
I mean the jdk can serialize over 14M rows ArrayList without any error, but it's slowly, fury can't with the below error:
ava.lang.NegativeArraySizeException: -2035644744

at io.fury.memory.MemoryBuffer.ensure(MemoryBuffer.java:1877)
at io.fury.memory.MemoryBuffer.grow(MemoryBuffer.java:1871)
at io.fury.resolver.MapRefResolver.writeRefOrNull(MapRefResolver.java:68)
at io.fury.Fury.writeRef(Fury.java:280)
at io.fury.serializer.CollectionSerializers$CollectionSerializer.writeElements(CollectionSerializers.java:138)
at io.fury.serializer.CollectionSerializers$CollectionSerializer.write(CollectionSerializers.java:115)
at io.fury.serializer.CollectionSerializers$CollectionSerializer.write(CollectionSerializers.java:65)
at io.fury.Fury.writeData(Fury.java:483)
at io.fury.Fury.writeRef(Fury.java:283)
at io.fury.Fury.serialize(Fury.java:233)
at io.fury.Fury.serialize(Fury.java:181)

**Comment by chaokunyang** [comment]
A minimal reproduction won't need 140m items, Maybe post your class def and mock some data will reproduce the failure. We need the reprod code to find out the root cause

**Comment by chaokunyang** [comment]
@tonysmz any update on this?
