### ISSUE TITLE
JAVA自关联的对象无法序列化，下面是对象的类结构

### ISSUE THREAD

**Issue by 16638112210** [alipay/fury#871]
自关联的对象无法序列化，下面是对象的类结构
```
@Data
public class SenseNodeBo implements Serializable {
    private SenseNodeBo nextNode;
}
```
执行逻级
```
  public static void main(String[] args) {
        ThreadSafeFury fury = Fury.builder()
                                  .withLanguage(Language.JAVA)
                                  .requireClassRegistration(false)
                                  .withRefTracking(false)
                                  .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
                                  .withAsyncCompilation(false)
                                  .buildThreadSafeFury();
        fury.getCurrentFury().register(SenseNodeBo.class);
        SenseNodeBo senseNodeBo = new SenseNodeBo();
        senseNodeBo.setNextNode(senseNodeBo);

        fury.serialize(senseNodeBo);
    }
```

报错日志
```
0:59:31.774 [main] WARN io.fury.Fury - Class registration isn't forced, unknown insecure classes can be deserialized. If the environment isn't 100% secure, please enable class registration by `FuryBuilder#requireClassRegistration(true)`.
10:59:31.793 [main] DEBUG io.fury.resolver.ClassResolver - `fury-format` dependency not included, skip adding serializer for class io.fury.format.vectorized.ArrowSerializers. If you want to use fury-format, please include fury-format dependency.
10:59:31.897 [main] INFO io.fury.Fury - Created new fury io.fury.Fury@7c1e2a9e
10:59:32.112 [main] INFO io.fury.codegen.CompileUnit - Generate code for com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552 took 76 ms.
10:59:32.262 [main] INFO io.fury.codegen.JaninoUtils - Compile [SenseNodeBoFuryCodec_354639575_248609774_262366552] take 148 ms
10:59:32.268 [main] DEBUG io.fury.codegen.CodeGenerator - Code stats for class com/sense/workflow/flow/core/SenseNodeBoFuryCodec_354639575_248609774_262366552.class is CodeStats{methodsSize={writeFields1$=280, <init>=171, readFields1$=170, readFields$=156, writeClassAndObject$=125, writeClassAndObject1$=125, writeClassAndObject2$=125, writeFields$=125, writeClassAndObject3$=125, writeClassAndObject4$=125, writeCollectionClassInfo$=119, read=79, write=62, class$=18}, constPoolSize=370}
Exception in thread "main" java.lang.StackOverflowError
	at io.fury.memory.MemoryBuffer.writeByte(MemoryBuffer.java:1064)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeFields$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:132)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.write(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:323)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeClassAndObject$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:81)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeFields$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:133)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.write(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:323)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeClassAndObject$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:81)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeFields$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:133)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.write(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:323)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeClassAndObject$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:81)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeFields$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:133)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.write(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:323)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeClassAndObject$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:81)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeFields$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:133)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.write(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:323)
	at com.sense.workflow.flow.core.SenseNodeBoFuryCodec_354639575_248609774_262366552.writeClassAndObject$(SenseNodeBoFuryCodec_354639575_248609774_262366552.java:8
```

**Comment by 16638112210** [comment]
原生JDK序列化是可以的，下面参考redisson中内置的SerializationCodec(JDK序列化)
```

import io.netty.buffer.ByteBuf;
import org.redisson.codec.SerializationCodec;

import java.io.IOException;

/**
 * @Date 8/15/23 10:45
 * @Created by zhaobo
 */
public class Test {
    public static void main(String[] args) {
        SenseNodeBo senseNodeBo = new SenseNodeBo();
        senseNodeBo.setNextNode(senseNodeBo);

        try {
            ByteBuf encode = new SerializationCodec().getValueEncoder()
                                           .encode(senseNodeBo);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }
}
```

**Comment by wangweipeng2** [comment]
> .withRefTracking(false)

The senseNodeBo references itself, so you need to enable the reference through withRefTracking(true)

**Comment by wangweipeng2** [comment]
```Java
package io.fury;
import io.fury.serializer.CompatibleMode;
import lombok.Data;

import java.io.IOException;

@Data
class SenseNodeBo {
  private SenseNodeBo nextNode;
}

public class FuryTest {
  public static void main(String[] args) throws IOException {
    ThreadSafeFury fury = Fury.builder()
            .withLanguage(Language.JAVA)
            .requireClassRegistration(false)
            .withRefTracking(true)  
            .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
            .withAsyncCompilation(false)
            .buildThreadSafeFury();
    fury.getCurrentFury().register(SenseNodeBo.class);
    SenseNodeBo senseNodeBo = new SenseNodeBo();
    senseNodeBo.setNextNode(senseNodeBo);
    fury.serialize(senseNodeBo);
  }
}

```
![image](https://github.com/alipay/fury/assets/16490211/5bab94ec-f30e-4dfc-9bb1-dd9f17c31812)

@16638112210   I tested it on Java 8, and it worked fine.  Could you please try it on your machine?

**Comment by 16638112210** [comment]
好的  感谢老师

**Comment by wangweipeng2** [comment]
> 好的 感谢老师

^_^ 没有老师，大家相互交流。
