### ISSUE TITLE
serial error, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by humanmonkey** [alipay/fury#882]
1、Unable to identify which field has the problem。

2、exception：
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
  at com.taobao.adapter.common.dataobject.trade.AbilityResultTOFuryRefCodec_274866609_772574458_1685137613.writeFields8$(AbilityResultTOFuryRefCodec_274866609_772574458_1685137613.java:777)
  at com.taobao.adapter.common.dataobject.trade.AbilityResultTOFuryRefCodec_274866609_772574458_1685137613.write(AbilityResultTOFuryRefCodec_274866609_772574458_1685137613.java:1571)
  at com.taobao.adapter.common.dataobject.trade.AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.writeClassAndObject2$(AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.java:159)
  at com.taobao.adapter.common.dataobject.trade.AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.writeFields2$(AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.java:198)
  at com.taobao.adapter.common.dataobject.trade.AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.write(AbilityResultTOGroupFuryRefCodec_274866609_772574458_1511574987.java:291)
  at com.alibaba.delivery.logistics.entity.params.targets.DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.writeClassAndObject35$(DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.java:1824)
  at com.alibaba.delivery.logistics.entity.params.targets.DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.writeFields19$(DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.java:1852)
  at com.alibaba.delivery.logistics.entity.params.targets.DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.write(DeliveryCarrierDTOFuryRefCodec_274866609_772574458_1253138594.java:2866)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.writeClassAndObject9$(DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.java:371)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.writeFields3$(DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.java:398)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.write(DeliveryCarrierDOFuryRefCodec_274866609_772574458_314439946.java:904)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.writeClassAndObject12$(DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.java:554)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.writeFields5$(DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.java:593)
  at com.alibaba.delivery.logistics.entity.core.targets.DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.write(DeliveryPackageDOFuryRefCodec_274866609_772574458_1023687807.java:1774)
  at io.fury.Fury.writeData(Fury.java:457)
  at io.fury.Fury.writeReferencableToJava(Fury.java:272)
  at io.fury.Fury.serializeInternal(Fury.java:243)
  at io.fury.Fury.serialize(Fury.java:180)
  at io.fury.Fury.serialize(Fury.java:173)
  at io.fury.ThreadSafeFury.serialize(ThreadSafeFury.java:50)
  at com.alibaba.delivery.logistics.common.utils.FuryUtil.serialize(FuryUtil.java:16)

3、 code:
 byte[] DeliveryPackageDOByte = FuryUtil.serialize(deliveryPackageDO);

public class FuryUtil {

    private static ThreadSafeFury fury = Fury.builder()
            .withLanguage(Language.JAVA)
            .withReferenceTracking(true)
            .disableSecureMode()
            .buildThreadSafeFury();

    public static byte[] serialize(Object obj){
        return fury.serialize(obj);
    }
}

**Comment by chaokunyang** [comment]
Is the class consistent between serialization and deserialization peer?

**Comment by chaokunyang** [comment]
Could you share your class definition here? A minimal reproduction example will be better to figure out what happened

**Comment by chaokunyang** [comment]
The user data has a bug which escape the Java generics
