### ISSUE TITLE
Create compatible serializer failed, can't get field offset on a record class

### ISSUE THREAD

**Issue by cdxf** [alipay/fury#911]
**Describe the bug**
Can't serialize with-args constructor Java record

**To Reproduce**
```
(Run and compiled with JDK 19, have not tried other versions)
- Fury 0.1.1

public class TestFury {
    public record Test(List<String> list) {
    }
    public static void main(String[] args) {
        Fury f = Fury.builder()
                .requireClassRegistration(false)
                .withRefTracking(true)
                .withAsyncCompilation(true)
                .withCompatibleMode(CompatibleMode.COMPATIBLE)
                .withLanguage(Language.JAVA).build();
        f.serialize(new Test(List.of()));
    }
}
```
Call stack:
```
Exception in thread "main" java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.util.List com.TestFury$Test.test
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at io.fury.util.UnsafeFieldAccessor.<init>(UnsafeFieldAccessor.java:45)
	at io.fury.resolver.FieldResolver$FieldInfo.<init>(FieldResolver.java:720)
	at io.fury.resolver.FieldResolver$CollectionFieldInfo.<init>(FieldResolver.java:869)
	at io.fury.resolver.FieldResolver$FieldInfo.of(FieldResolver.java:750)
	at io.fury.resolver.FieldResolver.<init>(FieldResolver.java:310)
	at io.fury.resolver.FieldResolver.of(FieldResolver.java:199)
	at io.fury.resolver.FieldResolver.of(FieldResolver.java:188)
	at io.fury.resolver.ClassResolver.getFieldResolver(ClassResolver.java:922)
	at io.fury.serializer.CompatibleSerializer.<init>(CompatibleSerializer.java:68)
	at io.fury.serializer.Serializers.newSerializer(Serializers.java:61)
	at io.fury.resolver.ClassResolver.createSerializer(ClassResolver.java:1068)
	at io.fury.resolver.ClassResolver.getOrUpdateClassInfo(ClassResolver.java:1009)
	at io.fury.Fury.writeRef(Fury.java:282)
	at io.fury.Fury.serialize(Fury.java:234)
	at io.fury.Fury.serialize(Fury.java:182)
	at com.TestFury.main(TestFury.java:19)
java.lang.RuntimeException: Create compatible serializer failed, 
class: class com.TestFury$Test
	at io.fury.serializer.CodegenSerializer.loadCompatibleCodegenSerializer(CodegenSerializer.java:56)
	at io.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$4(ClassResolver.java:872)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.util.List com.TestFury$Test.test
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at io.fury.util.UnsafeFieldAccessor.<init>(UnsafeFieldAccessor.java:45)
	at io.fury.resolver.FieldResolver$FieldInfo.<init>(FieldResolver.java:720)
	at io.fury.resolver.FieldResolver$CollectionFieldInfo.<init>(FieldResolver.java:869)
	at io.fury.resolver.FieldResolver$FieldInfo.of(FieldResolver.java:750)
	at io.fury.resolver.FieldResolver.<init>(FieldResolver.java:310)
	at io.fury.resolver.FieldResolver.of(FieldResolver.java:199)
	at io.fury.builder.CodecUtils.loadOrGenCompatibleCodecClass(CodecUtils.java:53)
	at io.fury.serializer.CodegenSerializer.loadCompatibleCodegenSerializer(CodegenSerializer.java:53)
	... 7 more
Exception in thread "fury-jit-compiler-1" java.lang.RuntimeException: Create compatible serializer failed, 
class: class com.TestFury$Test
	at io.fury.serializer.CodegenSerializer.loadCompatibleCodegenSerializer(CodegenSerializer.java:56)
	at io.fury.resolver.ClassResolver.lambda$getObjectSerializerClass$4(ClassResolver.java:872)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.UnsupportedOperationException: can't get field offset on a record class: private final java.util.List com.TestFury$Test.test
	at jdk.unsupported/sun.misc.Unsafe.objectFieldOffset(Unsafe.java:655)
	at io.fury.util.UnsafeFieldAccessor.<init>(UnsafeFieldAccessor.java:45)
	at io.fury.resolver.FieldResolver$FieldInfo.<init>(FieldResolver.java:720)
	at io.fury.resolver.FieldResolver$CollectionFieldInfo.<init>(FieldResolver.java:869)
	at io.fury.resolver.FieldResolver$FieldInfo.of(FieldResolver.java:750)
	at io.fury.resolver.FieldResolver.<init>(FieldResolver.java:310)
	at io.fury.resolver.FieldResolver.of(FieldResolver.java:199)
	at io.fury.builder.CodecUtils.loadOrGenCompatibleCodecClass(CodecUtils.java:53)
	at io.fury.serializer.CodegenSerializer.loadCompatibleCodegenSerializer(CodegenSerializer.java:53)
	... 7 more
```

**Comment by chaokunyang** [comment]
Hi @cdxf , record class has been supported in snapshot version, could you try whether that works?

**Comment by cdxf** [comment]
Thanks, works with snapshot version

**Comment by chaokunyang** [comment]
FYI, we'll release this support in next days.
