### ISSUE TITLE
[Java] fury 0.2.0 does not work properly in dubbo

### ISSUE THREAD

**Issue by T-baby** [alipay/fury#997]
**Describe the bug**
```java
Caused by: java.lang.NoSuchMethodError: 'io.fury.Fury$FuryBuilder io.fury.Fury.builder()'
 at org.furyio.serialization.dubbo.FurySerialization.lambda$null$0(FurySerialization.java:23)
 at io.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:93)
 at io.fury.util.LoaderBinding.setClassLoader(LoaderBinding.java:65)
 at org.furyio.serialization.dubbo.BaseFurySerialization.serialize(BaseFurySerialization.java:27)
 at org.apache.dubbo.common.serialize.DefaultSerializationExceptionWrapper.serialize(DefaultSerializationExceptionWrapper.java:51)
 at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:269)
 at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:79)
 at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:51)
 at org.apache.dubbo.remoting.transport.netty4.NettyChannel.send(NettyChannel.java:192)
 ... 120 more
```

**Expected behavior**
After fury is upgraded to 0.2.0, dubbo server and caller will give an error when using fury as serialization and deserialization.
dubbo-serialization-fury version is `0.1.2`.

It may be related to the position adjustment of CompatibleMode class after fury upgrade. https://github.com/fury-project/dubbo-serialization-fury/pull/13

**Environment (please complete the following information):**
openjdk version "17.0.8.1" 2023-08-24
IBM Semeru Runtime Open Edition 17.0.8.1 (build 17.0.8.1+1)
Eclipse OpenJ9 VM 17.0.8.1 (build openj9-0.40.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20230824_513 (JIT enabled, AOT enabled)
OpenJ9   - d12d10c9e
OMR      - e80bff83b
JCL      - 8ecf238a124 based on jdk-17.0.8.1+1)

**Comment by chaokunyang** [comment]
Hi @T-baby , thanks for filing this issue, I just merged your PR https://github.com/fury-project/dubbo-serialization-fury/pull/13, and released new `dubbo-serialization-fury` version: https://github.com/fury-project/dubbo-serialization-fury/releases/tag/v0.2.0

The jar has been released to maven centrao repo, please try it out, let us know if you have further issues.

**Comment by T-baby** [comment]
I have tested by myself, `dubbo-serialization-fury` and `fury-core` can be used normally when their dependencies are 0.2.0.
